name: Build report

on:
  workflow_run:
    workflows:
      - "build"
    types:
      - completed

permissions:
  actions: write
  checks: write
  pull-requests: write

env:
  TEST_REPORTS_ARTIFACT_NAME: will-be-read-from-env-file
  PR_NUMBER_ARTIFACT_NAME: will-be-read-from-env-file
  TEST_REPORT_NAME: will-be-read-from-env-file


jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment variables
        uses: ./.github/actions/setup-env

      - name: Download "${{ env.PR_NUMBER_ARTIFACT_NAME }}" from run ${{ github.event.workflow_run.id }}
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          name: ${{ env.PR_NUMBER_ARTIFACT_NAME }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Set PR number
        id: get-pr-number
        run: |
          echo "pr-number=$(cat pr-number.txt)" | tee "${GITHUB_OUTPUT}"
          rm -rf pr-number.txt

      - name: Publish reports
        uses: turing85/publish-report@feature/run-id-and-pr-number
        with:
          comment-message-pr-number: ${{ steps.get-pr-number.outputs.pr-number }}
          download-artifact-name: ${{ env.TEST_REPORTS_ARTIFACT_NAME }}
          download-artifact-run-id: ${{ github.event.workflow_run.id }}
          report-name: ${{ env.TEST_REPORT_NAME }}
          report-path: '**/target/**/TEST*.xml'
